### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by llcyb3rK1ttyll** [Stevekovix/esx_PoliceArmory#1]
Notifications are on french even if i changed them to german. the notification now shows 2 times. once in french and once in german

**Comment by Stevekovix** [comment]
Can you tell me where you made the changes?

**Comment by llcyb3rK1ttyll** [comment]
I made the changes in the server sided file foe the notifications for take and bring back weapon

**Comment by Stevekovix** [comment]
Did you see that the translations were in the config

**Comment by llcyb3rK1ttyll** [comment]
yeah but that translation i did was from the server lua. and even if i search the whole folder for the french part, nothin can be found

**Comment by llcyb3rK1ttyll** [comment]
i also deleted server cache and searched everything for the french part but i cant find anything, that is the weird thing about this

**Comment by llcyb3rK1ttyll** [comment]
https://gyazo.com/5887aa93620ec56aed33ae93ab6a5129

see it shows the notification twice. the weird thing that the bottom on is the translated and the other just appears out of nowhere
